[tool.poetry]
name = "ga4-gsc-joiner"
version = "0.1.0"
description = ""
authors = ["dom-devel <dom_woodman@msn.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.32.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
